services:
  web:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '5000:5000'
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: decider
      DB_PORT: 5432
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASS: admin
      CART_ENC_KEY: 12345678901234567890123456789012
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: decider
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d decider"]
      interval: 10s
      timeout: 5s
      retries: 5
